/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConvertDiffusersOptions
 */
export interface ConvertDiffusersOptions {
    /**
     * 
     * @type {string}
     * @memberof ConvertDiffusersOptions
     */
    model_id: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertDiffusersOptions
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertDiffusersOptions
     */
    reference_model?: string;
    /**
     * 
     * @type {string}
     * @memberof ConvertDiffusersOptions
     */
    hf_token?: string;
}

/**
 * Check if a given object implements the ConvertDiffusersOptions interface.
 */
export function instanceOfConvertDiffusersOptions(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "model_id" in value;

    return isInstance;
}

export function ConvertDiffusersOptionsFromJSON(json: any): ConvertDiffusersOptions {
    return ConvertDiffusersOptionsFromJSONTyped(json, false);
}

export function ConvertDiffusersOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConvertDiffusersOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model_id': json['model_id'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'reference_model': !exists(json, 'reference_model') ? undefined : json['reference_model'],
        'hf_token': !exists(json, 'hf_token') ? undefined : json['hf_token'],
    };
}

export function ConvertDiffusersOptionsToJSON(value?: ConvertDiffusersOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_id': value.model_id,
        'filename': value.filename,
        'reference_model': value.reference_model,
        'hf_token': value.hf_token,
    };
}

