/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiffusersConvertResponseModel
 */
export interface DiffusersConvertResponseModel {
    /**
     * 
     * @type {string}
     * @memberof DiffusersConvertResponseModel
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DiffusersConvertResponseModel
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof DiffusersConvertResponseModel
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof DiffusersConvertResponseModel
     */
    output: string;
}

/**
 * Check if a given object implements the DiffusersConvertResponseModel interface.
 */
export function instanceOfDiffusersConvertResponseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "output" in value;

    return isInstance;
}

export function DiffusersConvertResponseModelFromJSON(json: any): DiffusersConvertResponseModel {
    return DiffusersConvertResponseModelFromJSONTyped(json, false);
}

export function DiffusersConvertResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiffusersConvertResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'output': json['output'],
    };
}

export function DiffusersConvertResponseModelToJSON(value?: DiffusersConvertResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': value.data,
        'output': value.output,
    };
}

